@startuml
start
:Construir URL / parámetros;
:Enviar request HTTP;

if (HTTP status == 200?) then (sí)
    :Guardar HTML/JSON bruto (raw data);

    :Parsear contenido (extract);

    if (Datos válidos?) then (sí)
        :Transformar datos;
        :Guardar datos;

        :Loggear éxito;
        :Notificar éxito;
    else (no)
        :Loggear error de validación;
        :Notificar fallo en validación;
    endif

else (no)
    :Loggear fallo HTTP;
    :Notificar error HTTP;
endif

stop

@enduml